-- =============================================================================
-- derive/gap_buffer_factory.lua
-- Nebula GUI Compiler — Phase 3.6
--
-- 编译期泛型宏：nebula_gen_gap_buffer_type(N)
--
-- 从 gap_buffer.nelua 的 ##[[ ]] 块中提取，作为独立 Lua 模块加载。
-- 这样所有 require "nebula_core" 的文件都能在编译期使用此函数，
-- 无需手动 require "gap_buffer"。
--
-- 用法（在 .nelua 文件的编译期块中）：
--   ##[[ local _buf_type, _buf_src = nebula_gen_gap_buffer_type(255) ]]
--   ##[[ for _, _s in ipairs(aster.parse(_buf_src, "<gap_buffer:255>")) do inject_statement(_s) end ]]
-- =============================================================================

function nebula_gen_gap_buffer_type(capacity)
  assert(type(capacity) == "number" and capacity > 0 and capacity <= 65535,
    ("nebula_gen_gap_buffer_type: capacity must be 1..65535, got %s"):format(tostring(capacity)))
  local type_name = ("NebulaBuf%d"):format(capacity)
  -- 防止重复生成同一容量的类型
  if _nebula_gap_buf_types and _nebula_gap_buf_types[type_name] then
    return type_name, ""
  end
  _nebula_gap_buf_types = _nebula_gap_buf_types or {}
  _nebula_gap_buf_types[type_name] = true
  local lines = {}
  table.insert(lines, ("-- [gap_buffer] %s (capacity=%d)"):format(type_name, capacity))
  table.insert(lines, ("global %s = @record{"):format(type_name))
  table.insert(lines, ("  buf:       [%d]uint8,"):format(capacity + 1))
  table.insert(lines, ("  gap_start: uint16,"))
  table.insert(lines, ("  gap_end:   uint16,"))
  table.insert(lines, ("  capacity:  uint16,"))
  table.insert(lines, "}")
  table.insert(lines, "")
  table.insert(lines, ("function %s:init()"):format(type_name))
  table.insert(lines, ("  self.gap_start = 0"))
  table.insert(lines, ("  self.gap_end   = %d"):format(capacity))
  table.insert(lines, ("  self.capacity  = %d"):format(capacity))
  table.insert(lines, ("  self.buf[0]    = 0"))
  table.insert(lines, "end")
  table.insert(lines, "")
  table.insert(lines, ("function %s:len(): uint16"):format(type_name))
  table.insert(lines, ("  return self.capacity - (self.gap_end - self.gap_start)"))
  table.insert(lines, "end")
  table.insert(lines, "")
  table.insert(lines, ("function %s:is_full(): boolean"):format(type_name))
  table.insert(lines, ("  return self.gap_start == self.gap_end"))
  table.insert(lines, "end")
  table.insert(lines, "")
  table.insert(lines, ("function %s:cursor(): uint16"):format(type_name))
  table.insert(lines, ("  return self.gap_start"))
  table.insert(lines, "end")
  table.insert(lines, "")
  table.insert(lines, ("function %s:insert_char(ch: uint8): boolean"):format(type_name))
  table.insert(lines, ("  if self:is_full() then return false end"))
  table.insert(lines, ("  self.buf[self.gap_start] = ch"))
  table.insert(lines, ("  self.gap_start = self.gap_start + 1"))
  table.insert(lines, ("  return true"))
  table.insert(lines, "end")
  table.insert(lines, "")
  table.insert(lines, ("function %s:delete_before(): boolean"):format(type_name))
  table.insert(lines, ("  if self.gap_start == 0 then return false end"))
  table.insert(lines, ("  self.gap_start = self.gap_start - 1"))
  table.insert(lines, ("  return true"))
  table.insert(lines, "end")
  table.insert(lines, "")
  table.insert(lines, ("function %s:delete_after(): boolean"):format(type_name))
  table.insert(lines, ("  if self.gap_end >= self.capacity then return false end"))
  table.insert(lines, ("  self.gap_end = self.gap_end + 1"))
  table.insert(lines, ("  return true"))
  table.insert(lines, "end")
  table.insert(lines, "")
  table.insert(lines, ("function %s:move_cursor_left(): boolean"):format(type_name))
  table.insert(lines, ("  if self.gap_start == 0 then return false end"))
  table.insert(lines, ("  self.gap_end   = self.gap_end   - 1"))
  table.insert(lines, ("  self.buf[self.gap_end] = self.buf[self.gap_start - 1]"))
  table.insert(lines, ("  self.gap_start = self.gap_start - 1"))
  table.insert(lines, ("  return true"))
  table.insert(lines, "end")
  table.insert(lines, "")
  table.insert(lines, ("function %s:move_cursor_right(): boolean"):format(type_name))
  table.insert(lines, ("  if self.gap_end >= self.capacity then return false end"))
  table.insert(lines, ("  self.buf[self.gap_start] = self.buf[self.gap_end]"))
  table.insert(lines, ("  self.gap_start = self.gap_start + 1"))
  table.insert(lines, ("  self.gap_end   = self.gap_end   + 1"))
  table.insert(lines, ("  return true"))
  table.insert(lines, "end")
  table.insert(lines, "")
  table.insert(lines, ("function %s:move_cursor_home()"):format(type_name))
  table.insert(lines, ("  while self.gap_start > 0 do"))
  table.insert(lines, ("    self.gap_end   = self.gap_end   - 1"))
  table.insert(lines, ("    self.buf[self.gap_end] = self.buf[self.gap_start - 1]"))
  table.insert(lines, ("    self.gap_start = self.gap_start - 1"))
  table.insert(lines, ("  end"))
  table.insert(lines, "end")
  table.insert(lines, "")
  table.insert(lines, ("function %s:move_cursor_end()"):format(type_name))
  table.insert(lines, ("  while self.gap_end < self.capacity do"))
  table.insert(lines, ("    self.buf[self.gap_start] = self.buf[self.gap_end]"))
  table.insert(lines, ("    self.gap_start = self.gap_start + 1"))
  table.insert(lines, ("    self.gap_end   = self.gap_end   + 1"))
  table.insert(lines, ("  end"))
  table.insert(lines, "end")
  table.insert(lines, "")
  table.insert(lines, ("function %s:flatten(out: *[0]uint8, max_out: uint16): uint16"):format(type_name))
  table.insert(lines, ("  local n: uint16 = 0"))
  table.insert(lines, ("  local i: uint16 = 0"))
  table.insert(lines, ("  while i < self.gap_start and n < max_out do"))
  table.insert(lines, ("    out[n] = self.buf[i]"))
  table.insert(lines, ("    i = i + 1"))
  table.insert(lines, ("    n = n + 1"))
  table.insert(lines, ("  end"))
  table.insert(lines, ("  i = self.gap_end"))
  table.insert(lines, ("  while i < self.capacity and n < max_out do"))
  table.insert(lines, ("    out[n] = self.buf[i]"))
  table.insert(lines, ("    i = i + 1"))
  table.insert(lines, ("    n = n + 1"))
  table.insert(lines, ("  end"))
  table.insert(lines, ("  out[n] = 0"))
  table.insert(lines, ("  return n"))
  table.insert(lines, "end")
  table.insert(lines, "")
  table.insert(lines, ("function %s:clear()"):format(type_name))
  table.insert(lines, ("  self.gap_start = 0"))
  table.insert(lines, ("  self.gap_end   = self.capacity"))
  table.insert(lines, "end")
  table.insert(lines, "")
  table.insert(lines, ("-- [gap_buffer] %s: delete_range (Phase 3.6.3)"):format(type_name))
  table.insert(lines, ("function %s:delete_range(sel_start: uint32, sel_end: uint32): void"):format(type_name))
  table.insert(lines,  "  if sel_start >= sel_end then return end")
  table.insert(lines,  "  while self.gap_start > (@uint16)(sel_start) do")
  table.insert(lines,  "    self.gap_end   = self.gap_end   - 1")
  table.insert(lines,  "    self.buf[self.gap_end] = self.buf[self.gap_start - 1]")
  table.insert(lines,  "    self.gap_start = self.gap_start - 1")
  table.insert(lines,  "  end")
  table.insert(lines,  "  while self.gap_start < (@uint16)(sel_start) do")
  table.insert(lines,  "    self.buf[self.gap_start] = self.buf[self.gap_end]")
  table.insert(lines,  "    self.gap_start = self.gap_start + 1")
  table.insert(lines,  "    self.gap_end   = self.gap_end   + 1")
  table.insert(lines,  "  end")
  table.insert(lines,  "  local k: uint32 = sel_end - sel_start")
  table.insert(lines,  "  local j: uint32 = 0")
  table.insert(lines,  "  while j < k do")
  table.insert(lines,  "    if self.gap_end < self.capacity then")
  table.insert(lines,  "      self.gap_end = self.gap_end + 1")
  table.insert(lines,  "    end")
  table.insert(lines,  "    j = j + 1")
  table.insert(lines,  "  end")
  table.insert(lines,  "end")
  table.insert(lines, "")
  return type_name, table.concat(lines, "\n")
end

return "nebula_gap_buffer_factory_v0.1_phase3.6"
