/*
 * fixture_shader.h
 * Auto-generated by tools/export_shader_fixture.nelua (Phase 2.2)
 * DO NOT EDIT — regenerate with: nelua -L src tools/export_shader_fixture.nelua
 */
#ifndef NEBULA_FIXTURE_SHADER_H
#define NEBULA_FIXTURE_SHADER_H

/* ── Uniform 布局（与 WGSL struct Uniforms 严格对应） ── */
typedef struct { float x, y; }       Vec2;
typedef struct { float r, g, b, a; } Color;

typedef struct {
    Vec2     pos;              /* offset  0 */
    Vec2     size;             /* offset  8 */
    float    radius;           /* offset 16 */
    float    _pad0;            /* offset 20 */
    float    _pad1;            /* offset 24 */
    float    _pad2;            /* offset 28 */
    Color    bg_color;         /* offset 32 */
    Color    border_color;     /* offset 48 */
    float    border_width;     /* offset 64 */
    float    _pad3;            /* offset 68 */
    float    _pad4;            /* offset 72 */
    float    _pad5;            /* offset 76 */
    Vec2     viewport;         /* offset 80 */
    float    _pad6;            /* offset 88 */
    float    _pad7;            /* offset 92 */
} NebulaRectUniforms;      /* total: 96 bytes */

/* ── WGSL 着色器源码（由着色器组合器自动生成） ── */
static const char FIXTURE_WGSL[] =
"struct Uniforms {\n"
"  pos:         vec2<f32>,  // offset 0\n"
"  size:        vec2<f32>,  // offset 8\n"
"  radius:      f32,  // offset 16\n"
"  _pad0:       f32,  // offset 20\n"
"  _pad1:       f32,  // offset 24\n"
"  _pad2:       f32,  // offset 28\n"
"  bg_color:    vec4<f32>,  // offset 32\n"
"  border_color: vec4<f32>,  // offset 48\n"
"  border_width: f32,  // offset 64\n"
"  _pad3:       f32,  // offset 68\n"
"  _pad4:       f32,  // offset 72\n"
"  _pad5:       f32,  // offset 76\n"
"  viewport:    vec2<f32>,  // offset 80\n"
"  _pad6:       f32,  // offset 88\n"
"  _pad7:       f32,  // offset 92\n"
"}\n"
"\n"
"@group(0) @binding(0) var<uniform> u: Uniforms;\n"
"\n"
"struct VertexOutput {\n"
"  @builtin(position) clip_position: vec4<f32>,\n"
"}\n"
"\n"
"// 全屏三角形：3 个顶点覆盖整个 NDC 空间\n"
"@vertex\n"
"fn vs_main(@builtin(vertex_index) vi: u32) -> VertexOutput {\n"
"  var pos = array<vec2<f32>, 3>(\n"
"    vec2<f32>(-1.0, -1.0),\n"
"    vec2<f32>( 3.0, -1.0),\n"
"    vec2<f32>(-1.0,  3.0),\n"
"  );\n"
"  var out: VertexOutput;\n"
"  out.clip_position = vec4<f32>(pos[vi], 0.0, 1.0);\n"
"  return out;\n"
"}\n"
"\n"
"// SDF：圆角矩形的有符号距离函数\n"
"fn sdf_rounded_rect(p: vec2<f32>, b: vec2<f32>, r: f32) -> f32 {\n"
"  let q = abs(p) - b + vec2<f32>(r, r);\n"
"  return length(max(q, vec2<f32>(0.0, 0.0))) + min(max(q.x, q.y), 0.0) - r;\n"
"}\n"
"\n"
"@fragment\n"
"fn fs_main(in: VertexOutput) -> @location(0) vec4<f32> {\n"
"  // @builtin(position).xy 直接提供像素坐标（y 向下，原点在左上角）\n"
"  let pixel = in.clip_position.xy;\n"
"  let center = u.pos + u.size * 0.5;\n"
"  let p = pixel - center;\n"
"  let half_size = u.size * 0.5;\n"
"\n"
"  let dist = sdf_rounded_rect(p, half_size, u.radius);\n"
"\n"
"  // 抗锯齿：在边界附近平滑过渡（1px 宽度）\n"
"  let aa = 1.0;\n"
"  let fill_alpha  = 1.0 - smoothstep(-aa, aa, dist);\n"
"  let border_alpha = (1.0 - smoothstep(-aa, aa, dist + u.border_width)) - fill_alpha;\n"
"\n"
"  var color = u.bg_color * fill_alpha;\n"
"  color = color + u.border_color * border_alpha;\n"
"\n"
"  if color.a < 0.001 {\n"
"    discard;\n"
"  }\n"
"\n"
"  return color;\n"
"}\n"
;

/* Shader features: [radius, fill, border] */
/* Uniform size: 96 bytes */
/* Required passes: 1 */

#endif /* NEBULA_FIXTURE_SHADER_H */
