-- =============================================================================
-- nebula_codegen.lua
-- Phase 5.2 R3: Generated Code Preview Helper
--
-- This script provides instructions and utilities for inspecting generated code
-- produced by the Nebula GUI Compiler's compile-time metaprogram.
--
-- Usage:
--   lua tools/nebula_codegen.lua --help
--   lua tools/nebula_codegen.lua --verify
--
-- To inspect generated code, add the following directive in your .nelua source
-- AFTER all nebula_visual / nebula_app declarations:
--
--   ## print_source("all")             -- dump everything
--   ## print_source("visual", "MyVis") -- dump a specific visual
--   ## print_source("app", "MyApp")    -- dump a specific app
--   ## print_source("builtin")         -- dump all builtin producers
--
-- Then compile normally with nelua. The generated source will be printed to
-- stdout during compilation (in the ##-metaprogram phase).
-- =============================================================================

local mode = arg and arg[1] or nil

local function print_help()
  print([[
nebula_codegen.lua — Generated Code Preview Helper (Phase 5.2 R3)

This tool helps developers inspect code generated by the Nebula compile-time
metaprogram. Since code generation happens inside Nelua's ## blocks, the
recommended workflow is:

  1. Add a print_source directive in your .nelua file:

       ## print_source("all")
       ## print_source("visual", "ButtonVisual")
       ## print_source("app", "LoginApp")
       ## print_source("builtin")

  2. Compile with nelua:

       nelua your_app.nelua 2>&1 | less

  3. Look for lines starting with "[nebula] =====" in the output.

Modes:
  "all"      — Print all cached generated sources (visuals, apps, builtins)
  "visual"   — Print visual derivation output (pass name for specific visual)
  "app"      — Print app derivation output (pass name for specific app)
  "builtin"  — Print auto-generated builtin producers

Options:
  --help     Show this help message
  --verify   Check that source files contain the R3 infrastructure
]])
end

local function verify()
  local script_dir = debug.getinfo(1, "S").source:match("@(.*/)")
  local src_dir = script_dir and (script_dir .. "../src/") or "src/"

  local function read_file(path)
    local f = io.open(path, "r")
    if not f then return nil end
    local content = f:read("*a")
    f:close()
    return content
  end

  local ok = true
  local function check(desc, cond)
    if cond then
      print(("[PASS] %s"):format(desc))
    else
      print(("[FAIL] %s"):format(desc))
      ok = false
    end
  end

  local sugar = read_file(src_dir .. "nebula_sugar.nelua")
  local derive = read_file(src_dir .. "nebula_derive_engine.nelua")
  local apps = read_file(src_dir .. "nebula_apps.nelua")

  check("nebula_sugar.nelua readable", sugar ~= nil)
  check("nebula_derive_engine.nelua readable", derive ~= nil)
  check("nebula_apps.nelua readable", apps ~= nil)

  if sugar then
    check("_NEBULA_GENERATED_SOURCE init exists",
      sugar:find("_NEBULA_GENERATED_SOURCE") ~= nil)
    check("print_source function defined",
      sugar:find("function print_source") ~= nil)
    check("builtins cache in sugar",
      sugar:find("_NEBULA_GENERATED_SOURCE%.builtins") ~= nil)
  end

  if derive then
    check("visuals cache in derive engine",
      derive:find("_NEBULA_GENERATED_SOURCE%.visuals") ~= nil)
    check("apps cache in derive engine",
      derive:find("_NEBULA_GENERATED_SOURCE%.apps") ~= nil)
  end

  if apps then
    check("apps cache in nebula_apps",
      apps:find("_NEBULA_GENERATED_SOURCE%.apps") ~= nil)
  end

  if ok then
    print("\nAll checks passed. R3 infrastructure is in place.")
  else
    print("\nSome checks failed. See above.")
    os.exit(1)
  end
end

if mode == "--help" or mode == "-h" then
  print_help()
elseif mode == "--verify" then
  verify()
else
  print_help()
end
